apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-1
  region: us-east-1
  version: "1.30"

vpc:
  id: "vpc-01a110f76b1e37918"
  subnets:
    private:
      us-east-1a:
        id: "subnet-0e8e54614eb0cffcf"
      us-east-1b:
        id: "subnet-0d35edda7442a2128"
    public:
      us-east-1a:
        id: "subnet-0d701a07148031e0a"
      us-east-1b:
        id: "subnet-0b722df860dfbd495"

nodeGroups:
  - name: ng-1
    labels: { role: backend }
    instanceType: t3.small
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: eks-demo-key-pair
    iam:
      withAddonPolicies:
        imageBuilder: true
        awsLoadBalancerController: true
        autoScaler: true
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::253490763368:policy/AWSLoadBalancerControllerIAMPolicy
        - arn:aws:iam::253490763368:policy/csi-eks-access-secrets-manager