apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "rdspass3_1"
          objectType: "secretsmanager"
        - objectName: "rdspass2_1"
          objectType: "secretsmanager"
        - objectName: "rdspass1_2"
          objectType: "secretsmanager"
        - objectName: "rdspass1_1"
          objectType: "secretsmanager"
        - objectName: "rds!db-bbcf8143-0e8e-45b3-8cd1-965894fe1275"
          objectType: "secretsmanager"
          
        